name: Pull request

on:
  pull_request:

jobs:

  reproduce-ipynb:
    if: github.event.pull_request.base.ref == 'jupyter-reproducible-document'
    uses: ./.github/workflows/reproducible-doc.yml
    with:
      notebook-path: reproducible_document_template.ipynb

  reproduce-qmd:
    if: github.event.pull_request.base.ref == 'r-reproducible-document'
    uses: ./.github/workflows/reproducible-doc.yml
    with:
      notebook-path: reproducible_document_template.qmd
